services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    volumes:
      - ../www/:/var/www/html
    ports:
      - "${APACHE_PORT}:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
